name: Run Action from Another Repo

on:
  push:
    branches:
      - main  # mainブランチにpushされたときにトリガーされます
  pull_request:
    branches:
      - main  # PRがmainに対して作成されたときにトリガーされます
  workflow_dispatch:

jobs:
  run_action:
    runs-on: ubuntu-latest  # 使用するOS
    steps:
      # 現在のリポジトリをチェックアウト
      - name: Checkout current repository
        uses: actions/checkout@v2

      # `actions/common/load-config/action.yaml` のアクションを実行
      - name: Run the action from actionDemo repo
        id: load-config
        uses: TingWangPass/actionDemo/.github/actions/common/load-config@main
        with:
          config_file: .github/actions/config/tst-config.yaml

      - name: Show Output
        run: |
          echo "Outputs:"
          echo "jdk: ${{ steps.load-config.outputs.jdk }}"
          echo "slack_teamDomain: ${{ steps.load-config.outputs.slack_teamDomain }}"  # アンダースコア形式で表示
          echo "slack_webhookUrl: ${{ steps.load-config.outputs.slack_webhookUrl }}"  # アンダースコア形式で表示
          echo "parameter_store: ${{ steps.load-config.outputs.parameter_store }}"  # test1 オブジェクト全体を表示
          echo "secret_manager: ${{ steps.load-config.outputs.secret_manager }}"  # test1 オブジェクト全体を表示