name: Run Action from Another Repo

on:
  push:
    branches:
      - main  # mainブランチにpushされたときにトリガーされます
  pull_request:
    branches:
      - main  # PRがmainに対して作成されたときにトリガーされます
  workflow_dispatch:

jobs:
  run_action:
    runs-on: ubuntu-latest  # 使用するOS
    steps:
      # 現在のリポジトリをチェックアウト
      - name: Checkout current repository
        uses: actions/checkout@v2

      # `actions/common/load-config/action.yaml` のアクションを実行
      - name: Run the action from actionDemo repo
        id: load-config
        uses: TingWangPass/actionDemo/.github/actions/common/load-config@main
        with:
          config_file: .github/actions/config/tst-config.yaml

      - name: Read secrets from ps
        id: get-aws-ps-param
        uses: TingWangPass/actionDemo/.github/actions/common/get-aws-ps-param@main
        with:
         