name: Run Action from Another Repo

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  workflow_dispatch:

jobs:
  run_action:
    runs-on: ubuntu-latest  # 使用するOS
    steps:
      # 現在のリポジトリをチェックアウト
      - name: Checkout current repository
        uses: actions/checkout@v4

      # `actions/common/load-config/action.yaml` のアクションを実行
      - name: Run the action from bizcom common manage cicd repo
        id: load-config
        uses: SECOM-BP/bizcom-common-manage-cicd/.github/actions/common/load-config@prd
        with:
          config_file: .github/actions/config/tst-config.yaml@tst   

      # temperary comment out
      # - name: Run the get-aws-ps-param from actionDemo repo
      #   id: get-aws-ps-param
      #   uses: TingWangPass/actionDemo/.github/actions/common/get-aws-ps-param@main
      #   with:
      #     input_json: ${{ toJson(fromJson(steps.load-config.outputs.github_output).parameter_store) }}

      # - name: Show Output2
      #   run: |
      #     echo "Outputs:"
      #     echo "user: ${{ fromJson(steps.get-aws-ps-param.outputs.github_output).user }}"
      #     echo "password: ${{ fromJson(steps.get-aws-ps-param.outputs.github_output).password }}"

      - name: Run frontend setup
        id: init-frontend
        uses: SECOM-BP/bizcom-common-manage-cicd/.github/actions/common/init-frontend/action.yaml@tst

      - name: 'Run ViTest'
        id: vitest
        run: |
          npx vitest --coverage.enabled true
          echo "process_result=$STATUS" >> $GITHUB_OUTPUT

      - name: Build pnpm
        id: build-pnpm
        if: steps.vitest.outputs.result == '0'
        run: |
          echo "Using app_properties_env: $app_properties_env"
          pnpm build             

      - name: Run frontend code analysis
        id: frontend-code-quality-analysis
        if: steps.build-pnpm.outputs.result == '0'
        uses: SECOM-BP/bizcom-common-manage-cicd/.github/actions/common/frontend-code-quality-analysis/action.yaml@feature/frontend-code-quality-analysis
        continue-on-error: true

      - name: Run sca sast analysis
        id: sca-sast-analysis
        if: always() && steps.frontend-code-quality-analysis.outputs.process_result != ''
        # temperary for test
        uses: SECOM-BP/bizcom-common-manage-cicd/.github/actions/common/sca-sast-analysis/action.yaml@tst

      - name: Generate AsciiDoc
        id: generate-asciidoc
        if: steps.frontend-code-quality-analysis.outputs.process_result == '0' && steps.sca-sast-analysis.outputs.process_result == '0'
        run: |
          echo "Generating AsciiDoc..."
          chmod +x gradlew && ./gradlew asciidoc

      # temperary path, need to change
      - name: Upload reports to Nexus
        if: always()
        shell: bash
        run: |
          echo "[NEXUS UPLOAD] Tests failed. Attempting to upload existing artifacts..."
          
          ARTIFACT_PATH="./dist/my-artifact.tar.gz"

          if [ -f "$ARTIFACT_PATH" ]; then
            echo "Found artifact: $ARTIFACT_PATH"
            curl -u "$NEXUS_USER:$NEXUS_PASSWORD" \
                --upload-file "$ARTIFACT_PATH" \
                https://your-nexus-host/repository/your-repo/my-artifact.tar.gz
          else
            echo "No artifact found at $ARTIFACT_PATH, skipping upload."
          fi